version: "3"
services:
  music-app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        # 此处默认从宿主机(host)环境变量中传参，在宿主机中需要提前配置 ACCESS_KEY_ID/ACCESS_KEY_SECRET 环境变量
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-hangzhou.aliyuncs.com
    ports:
      - 80:9090
